steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/faruk-kadir-spring-boot-demo', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'faruk-springboot', '--image', 'gcr.io/$PROJECT_ID/faruk-kadir-spring-boot-demo', '--region', 'us-west1', '--platform', 'managed']

images: ['gcr.io/$PROJECT_ID/spring-boot']
