steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/spring-boot', '.']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'faruk-kadir-spring-boot-demo', '--image', 'gcr.io/$PROJECT_ID/faruk-boot-demp', '--region', 'us-central1']
images: ['gcr.io/$PROJECT_ID/spring-boot']
